char* index_html = "<!DOCTYPE HTML>\n"
"<html>\n"
"<head>\n"
"<meta http-equiv='Content-Type' content='text/html; charset=utf-8' />\n"
"<meta name='viewport' content='width=device-width, minimum-scale=1.0, maximum-scale=1.0' />\n"
"<style>\n"
"\n"
"#emojiSender a:link {\n"
"	text-decoration: none;\n"
"}\n"
"\n"
"#emojiSender a:active {\n"
"	font-size: 70pt;\n"
"}\n"
"\n"
"\n"
"#emojiSender {\n"
"	text-align: \n"
"	padding-top: 20px;\n"
"	margin: 20px;\n"
"	font-size: 64pt;\n"
"\n"
"}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<script>\n"
"var getRange = function() {\n"
"	var x = document.getElementById('stepperRange').value;\n"
"    document.getElementById('demo').innerHTML = x;\n"
"    return x;\n"
"}\n"
"var rotate = function(times) {\n"
"	var xhr = new XMLHttpRequest();\n"
"	xhr.open('GET', 'rot?' + times);\n"
"	xhr.send();\n"
"};\n"
"var step = function(steps) {\n"
"	var xhr = new XMLHttpRequest();\n"
"	xhr.open('GET', 'step?' + steps);\n"
"	xhr.send();\n"
"};\n"
"var pos = function(angle) {\n"
"	var xhr = new XMLHttpRequest();\n"
"	xhr.open('GET', 'pos?' + angle);\n"
"	xhr.send();\n"
"};\n"
"var emoji = function(number) {\n"
"	var xhr = new XMLHttpRequest();\n"
"	xhr.open('GET', 'emoji?' + number);\n"
"	xhr.send();\n"
"};\n"
"</script>\n"
"<center>\n"
"\n"
"<H1>Top Secret Foxhole Control Panel</H1>\n"
"\n"
"Click an emoji to manifest it inside The Foxhole\n"
"\n"
"<div id='emojiSender'>\n"
"<!-- <a href='javascript:emoji(1);'>😀</a> -->\n"
"<a href='javascript:emoji(2);'>😂</a>\n"
"<a href='javascript:emoji(3);'>😜</a>\n"
"<a href='javascript:emoji(4);'>😘</a>\n"
"<a href='javascript:emoji(5);'>❤️</a>\n"
"<a href='javascript:emoji(6);'>😈</a>\n"
"<a href='javascript:emoji(7);'>😇</a>\n"
"<a href='javascript:emoji(8);'>😻</a>\n"
"</div>\n"
"\n"
"</center>\n"
"\n"
"<hr>\n"
"<!-- <h3>Ultra Top Secret Configuration Panel</h3>\n"
"<p>Rotate me <a href='javascript:rotate(1);'>once!</a></p>\n"
"\n"
"<p>Step me <a href='javascript:step(1);'>once!</a></p>\n"
"\n"
"<p><input id='stepperRange' type='range' min=0 max=360 step=1 value=0/></p>\n"
"\n"
"<p><div id='demo'></div></p>\n"
"\n"
"<script>\n"
"window.onload = function() {\n"
"	document.getElementById('stepperRange').addEventListener('change', function() {\n"
"		pos(getRange());\n"
"	})\n"
"}\n"
"</script> -->\n"
"</body></html>\n"
"";